version: '3.7'

services:
  postgres:
    image: postgres:12.1-alpine
    networks:
      - backend-private
    environment:
      POSTGRES_DB: mygiftlistrocks
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_password

  backend:
    image: cpodonnell/mygiftlistrocks:latest
    networks:
      - traefik-public
      - backend-private
    depends_on:
      - postgres
    environment:
      JWK_ENDPOINT: "https://mygiftlistrocks.auth0.com/.well-known/jwks.json"
      PORT: "8080"
      POSTGRES_DB: mygiftlistrocks
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.backend-redirect-websecure.redirectscheme.scheme=https"
        - "traefik.http.routers.backend-web.middlewares=backend-redirect-websecure"
        - "traefik.http.routers.backend-web.rule=Host(`mygiftlist.rocks`)"
        - "traefik.http.routers.backend-web.entrypoints=web"
        - "traefik.http.routers.backend-websecure.rule=Host(`mygiftlist.rocks`)"
        - "traefik.http.routers.backend-websecure.tls.certresolver=le"
        - "traefik.http.routers.backend-websecure.tls=true"
        - "traefik.http.routers.backend-websecure.tls.options=backend-options@file"
        - "traefik.http.routers.backend-websecure.entrypoints=websecure"
        - "traefik.http.services.backend-websecure.loadbalancer.server.port=8080"
        - "traefik.tls.options.backend-options.minversion=VersionTLS12"

networks:
  traefik-public:
    external: true
  backend-private:
    external: false

secrets:
  db_user:
    external: true
  db_password:
    external: true

volumes:
  db_data:
