FROM flyway/flyway:6.2.1-alpine

COPY migrations /flyway/sql

ENTRYPOINT ["/bin/sh"]

CMD ["-c", "/flyway/flyway -url=jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB} -user=$(cat ${POSTGRES_USER_FILE}) -password=$(cat ${POSTGRES_PASSWORD_FILE}) -connectRetries=60 migrate"]
