version: "3.7"
services:
  nginx:
    image: nginx:1.17.6-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./resources/public:/var/www/html
