apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
spec:
  template:
    spec:
      containers:
      - name: migrate-db
        image: cpodonnell/mygiftlistrocks:migrate-latest
        envFrom:
        - configMapRef:
            name: db-config
        volumeMounts:
        - name: db-secret
          mountPath: "/db/secrets"
          readOnly: true
      volumes:
      - name: db-secret
        secret:
          secretName: db-secret
      restartPolicy: Never
  backoffLimit: 4

